// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calculate_WAIC
Rcpp::List calculate_WAIC(arma::mat Y, arma::mat X, Rcpp::List mod, arma::mat splineS, arma::mat splineT, arma::uword burnin);
RcppExport SEXP _LFBayes_calculate_WAIC(SEXP YSEXP, SEXP XSEXP, SEXP modSEXP, SEXP splineSSEXP, SEXP splineTSEXP, SEXP burninSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type mod(modSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineS(splineSSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineT(splineTSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type burnin(burninSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_WAIC(Y, X, mod, splineS, splineT, burnin));
    return rcpp_result_gen;
END_RCPP
}
// calculate_BIC
Rcpp::List calculate_BIC(arma::mat Y, arma::mat X, Rcpp::List mod, arma::mat splineS, arma::mat splineT, arma::uword burnin, arma::uword thin);
RcppExport SEXP _LFBayes_calculate_BIC(SEXP YSEXP, SEXP XSEXP, SEXP modSEXP, SEXP splineSSEXP, SEXP splineTSEXP, SEXP burninSEXP, SEXP thinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type mod(modSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineS(splineSSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineT(splineTSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type thin(thinSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_BIC(Y, X, mod, splineS, splineT, burnin, thin));
    return rcpp_result_gen;
END_RCPP
}
// calculate_DIC
Rcpp::List calculate_DIC(arma::mat Y, arma::mat X, Rcpp::List mod, arma::mat splineS, arma::mat splineT, arma::uword burnin, arma::uword thin);
RcppExport SEXP _LFBayes_calculate_DIC(SEXP YSEXP, SEXP XSEXP, SEXP modSEXP, SEXP splineSSEXP, SEXP splineTSEXP, SEXP burninSEXP, SEXP thinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type mod(modSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineS(splineSSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineT(splineTSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type thin(thinSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_DIC(Y, X, mod, splineS, splineT, burnin, thin));
    return rcpp_result_gen;
END_RCPP
}
// calculate_BIC_Missing
Rcpp::List calculate_BIC_Missing(arma::field<arma::vec> Y, arma::mat X, arma::field<arma::uvec> observed, Rcpp::List mod, arma::mat splineS, arma::mat splineT, arma::uword burnin, arma::uword thin);
RcppExport SEXP _LFBayes_calculate_BIC_Missing(SEXP YSEXP, SEXP XSEXP, SEXP observedSEXP, SEXP modSEXP, SEXP splineSSEXP, SEXP splineTSEXP, SEXP burninSEXP, SEXP thinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::vec> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::uvec> >::type observed(observedSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type mod(modSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineS(splineSSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineT(splineTSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type thin(thinSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_BIC_Missing(Y, X, observed, mod, splineS, splineT, burnin, thin));
    return rcpp_result_gen;
END_RCPP
}
// calculate_DIC_Missing
Rcpp::List calculate_DIC_Missing(arma::field<arma::vec> Y, arma::mat X, arma::field<arma::uvec> observed, Rcpp::List mod, arma::mat splineS, arma::mat splineT, arma::uword burnin, arma::uword thin);
RcppExport SEXP _LFBayes_calculate_DIC_Missing(SEXP YSEXP, SEXP XSEXP, SEXP observedSEXP, SEXP modSEXP, SEXP splineSSEXP, SEXP splineTSEXP, SEXP burninSEXP, SEXP thinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::vec> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::uvec> >::type observed(observedSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type mod(modSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineS(splineSSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineT(splineTSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type thin(thinSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_DIC_Missing(Y, X, observed, mod, splineS, splineT, burnin, thin));
    return rcpp_result_gen;
END_RCPP
}
// test1
void test1(arma::field<arma::uvec> observed, arma::mat S);
RcppExport SEXP _LFBayes_test1(SEXP observedSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::uvec> >::type observed(observedSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    test1(observed, S);
    return R_NilValue;
END_RCPP
}
// eigenLF
Rcpp::List eigenLF(arma::mat splineS, arma::mat splineT, Rcpp::List mod, arma::uword numeig, int burnin);
RcppExport SEXP _LFBayes_eigenLF(SEXP splineSSEXP, SEXP splineTSEXP, SEXP modSEXP, SEXP numeigSEXP, SEXP burninSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type splineS(splineSSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineT(splineTSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type mod(modSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type numeig(numeigSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenLF(splineS, splineT, mod, numeig, burnin));
    return rcpp_result_gen;
END_RCPP
}
// eigenLFChains
Rcpp::List eigenLFChains(arma::mat splineS, arma::mat splineT, Rcpp::List mod, arma::uword numeig, int iter, int burnin, int nchains, arma::vec s, arma::vec t, double alpha);
RcppExport SEXP _LFBayes_eigenLFChains(SEXP splineSSEXP, SEXP splineTSEXP, SEXP modSEXP, SEXP numeigSEXP, SEXP iterSEXP, SEXP burninSEXP, SEXP nchainsSEXP, SEXP sSEXP, SEXP tSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type splineS(splineSSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineT(splineTSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type mod(modSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type numeig(numeigSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type nchains(nchainsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type s(sSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenLFChains(splineS, splineT, mod, numeig, iter, burnin, nchains, s, t, alpha));
    return rcpp_result_gen;
END_RCPP
}
// integrated_latent
arma::vec integrated_latent(arma::mat latent, arma::vec times);
RcppExport SEXP _LFBayes_integrated_latent(SEXP latentSEXP, SEXP timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type latent(latentSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type times(timesSEXP);
    rcpp_result_gen = Rcpp::wrap(integrated_latent(latent, times));
    return rcpp_result_gen;
END_RCPP
}
// integrated
arma::mat integrated(arma::mat spline, arma::vec times);
RcppExport SEXP _LFBayes_integrated(SEXP splineSEXP, SEXP timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type spline(splineSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type times(timesSEXP);
    rcpp_result_gen = Rcpp::wrap(integrated(spline, times));
    return rcpp_result_gen;
END_RCPP
}
// extract_eigenfn
Rcpp::List extract_eigenfn(arma::mat latent, arma::mat S, arma::mat H, arma::mat spline, arma::mat spline_int_sqrt, arma::mat spline_int_sqrt_inv, arma::mat spline_int, arma::vec latent_trapz, arma::uword numeig);
RcppExport SEXP _LFBayes_extract_eigenfn(SEXP latentSEXP, SEXP SSEXP, SEXP HSEXP, SEXP splineSEXP, SEXP spline_int_sqrtSEXP, SEXP spline_int_sqrt_invSEXP, SEXP spline_intSEXP, SEXP latent_trapzSEXP, SEXP numeigSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type latent(latentSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type H(HSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type spline(splineSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type spline_int_sqrt(spline_int_sqrtSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type spline_int_sqrt_inv(spline_int_sqrt_invSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type spline_int(spline_intSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type latent_trapz(latent_trapzSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type numeig(numeigSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_eigenfn(latent, S, H, spline, spline_int_sqrt, spline_int_sqrt_inv, spline_int, latent_trapz, numeig));
    return rcpp_result_gen;
END_RCPP
}
// getMarginalFunc
arma::mat getMarginalFunc(arma::mat& cov, int ns, int nt);
RcppExport SEXP _LFBayes_getMarginalFunc(SEXP covSEXP, SEXP nsSEXP, SEXP ntSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type cov(covSEXP);
    Rcpp::traits::input_parameter< int >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< int >::type nt(ntSEXP);
    rcpp_result_gen = Rcpp::wrap(getMarginalFunc(cov, ns, nt));
    return rcpp_result_gen;
END_RCPP
}
// getMarginalLong
arma::mat getMarginalLong(arma::mat cov, int ns, int nt);
RcppExport SEXP _LFBayes_getMarginalLong(SEXP covSEXP, SEXP nsSEXP, SEXP ntSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    Rcpp::traits::input_parameter< int >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< int >::type nt(ntSEXP);
    rcpp_result_gen = Rcpp::wrap(getMarginalLong(cov, ns, nt));
    return rcpp_result_gen;
END_RCPP
}
// mcmcWeak
Rcpp::List mcmcWeak(arma::field<arma::vec> y, arma::field<arma::vec> missing, arma::mat X, arma::mat splineS, arma::mat splineT, int q1, int q2, int iter, int thin, int burnin);
RcppExport SEXP _LFBayes_mcmcWeak(SEXP ySEXP, SEXP missingSEXP, SEXP XSEXP, SEXP splineSSEXP, SEXP splineTSEXP, SEXP q1SEXP, SEXP q2SEXP, SEXP iterSEXP, SEXP thinSEXP, SEXP burninSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::vec> >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::field<arma::vec> >::type missing(missingSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineS(splineSSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineT(splineTSEXP);
    Rcpp::traits::input_parameter< int >::type q1(q1SEXP);
    Rcpp::traits::input_parameter< int >::type q2(q2SEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmcWeak(y, missing, X, splineS, splineT, q1, q2, iter, thin, burnin));
    return rcpp_result_gen;
END_RCPP
}
// mcmcWeakChains
Rcpp::List mcmcWeakChains(arma::field<arma::vec> y, arma::field<arma::vec> missing, arma::mat X, arma::mat splineS, arma::mat splineT, int q1, int q2, int iter, int thin, int burnin, int nchains);
RcppExport SEXP _LFBayes_mcmcWeakChains(SEXP ySEXP, SEXP missingSEXP, SEXP XSEXP, SEXP splineSSEXP, SEXP splineTSEXP, SEXP q1SEXP, SEXP q2SEXP, SEXP iterSEXP, SEXP thinSEXP, SEXP burninSEXP, SEXP nchainsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::vec> >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::field<arma::vec> >::type missing(missingSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineS(splineSSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineT(splineTSEXP);
    Rcpp::traits::input_parameter< int >::type q1(q1SEXP);
    Rcpp::traits::input_parameter< int >::type q2(q2SEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type nchains(nchainsSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmcWeakChains(y, missing, X, splineS, splineT, q1, q2, iter, thin, burnin, nchains));
    return rcpp_result_gen;
END_RCPP
}
// mcmcWeakChainsPCA
Rcpp::List mcmcWeakChainsPCA(arma::field<arma::vec> y, arma::field<arma::vec> missing, arma::mat X, arma::mat splineS, arma::mat splineT, int q1, int q2, int iter, int thin, int burnin, int nchains);
RcppExport SEXP _LFBayes_mcmcWeakChainsPCA(SEXP ySEXP, SEXP missingSEXP, SEXP XSEXP, SEXP splineSSEXP, SEXP splineTSEXP, SEXP q1SEXP, SEXP q2SEXP, SEXP iterSEXP, SEXP thinSEXP, SEXP burninSEXP, SEXP nchainsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::vec> >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::field<arma::vec> >::type missing(missingSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineS(splineSSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineT(splineTSEXP);
    Rcpp::traits::input_parameter< int >::type q1(q1SEXP);
    Rcpp::traits::input_parameter< int >::type q2(q2SEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type nchains(nchainsSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmcWeakChainsPCA(y, missing, X, splineS, splineT, q1, q2, iter, thin, burnin, nchains));
    return rcpp_result_gen;
END_RCPP
}
// timesTwo
double timesTwo(NumericVector x);
RcppExport SEXP _LFBayes_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}
// convertToPrecision
arma::mat convertToPrecision(arma::vec Delta, arma::uword q1, arma::uword q2);
RcppExport SEXP _LFBayes_convertToPrecision(SEXP DeltaSEXP, SEXP q1SEXP, SEXP q2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type q1(q1SEXP);
    Rcpp::traits::input_parameter< arma::uword >::type q2(q2SEXP);
    rcpp_result_gen = Rcpp::wrap(convertToPrecision(Delta, q1, q2));
    return rcpp_result_gen;
END_RCPP
}
// updateBeta2
arma::mat updateBeta2(arma::mat E, arma::mat Eta, arma::mat X);
RcppExport SEXP _LFBayes_updateBeta2(SEXP ESEXP, SEXP EtaSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type E(ESEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(updateBeta2(E, Eta, X));
    return rcpp_result_gen;
END_RCPP
}
// updateBetaProd
void updateBetaProd(arma::cube& eta, arma::vec Delta, arma::mat& E, arma::mat& X, arma::mat& beta);
RcppExport SEXP _LFBayes_updateBetaProd(SEXP etaSEXP, SEXP DeltaSEXP, SEXP ESEXP, SEXP XSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type E(ESEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type beta(betaSEXP);
    updateBetaProd(eta, Delta, E, X, beta);
    return R_NilValue;
END_RCPP
}
// updateDelta3
arma::vec updateDelta3(arma::mat& Lambda, arma::mat& Phi, arma::vec Delta, double a1, double a2);
RcppExport SEXP _LFBayes_updateDelta3(SEXP LambdaSEXP, SEXP PhiSEXP, SEXP DeltaSEXP, SEXP a1SEXP, SEXP a2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< double >::type a2(a2SEXP);
    rcpp_result_gen = Rcpp::wrap(updateDelta3(Lambda, Phi, Delta, a1, a2));
    return rcpp_result_gen;
END_RCPP
}
// updateDeltaProdTemp
arma::vec updateDeltaProdTemp(arma::mat Lambda, arma::vec Delta, double a1, double a2);
RcppExport SEXP _LFBayes_updateDeltaProdTemp(SEXP LambdaSEXP, SEXP DeltaSEXP, SEXP a1SEXP, SEXP a2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< double >::type a2(a2SEXP);
    rcpp_result_gen = Rcpp::wrap(updateDeltaProdTemp(Lambda, Delta, a1, a2));
    return rcpp_result_gen;
END_RCPP
}
// updateE
arma::mat updateE(arma::mat beta);
RcppExport SEXP _LFBayes_updateE(SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateE(beta));
    return rcpp_result_gen;
END_RCPP
}
// updateEta
void updateEta(arma::mat& Lambda, arma::mat& Gamma, arma::vec sigma1, arma::vec sigma2, arma::mat H, arma::mat& splineS, arma::mat& splineT, arma::mat& y, double varphi, arma::mat& beta, arma::mat& X, arma::cube& eta);
RcppExport SEXP _LFBayes_updateEta(SEXP LambdaSEXP, SEXP GammaSEXP, SEXP sigma1SEXP, SEXP sigma2SEXP, SEXP HSEXP, SEXP splineSSEXP, SEXP splineTSEXP, SEXP ySEXP, SEXP varphiSEXP, SEXP betaSEXP, SEXP XSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type H(HSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type splineS(splineSSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type splineT(splineTSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type varphi(varphiSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type eta(etaSEXP);
    updateEta(Lambda, Gamma, sigma1, sigma2, H, splineS, splineT, y, varphi, beta, X, eta);
    return R_NilValue;
END_RCPP
}
// updateEtaSig
void updateEtaSig(arma::mat& Lambda, arma::mat& Gamma, arma::mat Sigma, arma::mat H, arma::mat& splineS, arma::mat& splineT, arma::mat& y, double varphi, arma::mat& beta, arma::mat& X, arma::cube& eta);
RcppExport SEXP _LFBayes_updateEtaSig(SEXP LambdaSEXP, SEXP GammaSEXP, SEXP SigmaSEXP, SEXP HSEXP, SEXP splineSSEXP, SEXP splineTSEXP, SEXP ySEXP, SEXP varphiSEXP, SEXP betaSEXP, SEXP XSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type H(HSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type splineS(splineSSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type splineT(splineTSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type varphi(varphiSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type eta(etaSEXP);
    updateEtaSig(Lambda, Gamma, Sigma, H, splineS, splineT, y, varphi, beta, X, eta);
    return R_NilValue;
END_RCPP
}
// updateEta2
arma::mat updateEta2(arma::mat Lambda, arma::mat Basis, arma::vec Sigma, arma::mat Data, arma::mat Beta, arma::mat X, double Varphi);
RcppExport SEXP _LFBayes_updateEta2(SEXP LambdaSEXP, SEXP BasisSEXP, SEXP SigmaSEXP, SEXP DataSEXP, SEXP BetaSEXP, SEXP XSEXP, SEXP VarphiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Basis(BasisSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Data(DataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Beta(BetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type Varphi(VarphiSEXP);
    rcpp_result_gen = Rcpp::wrap(updateEta2(Lambda, Basis, Sigma, Data, Beta, X, Varphi));
    return rcpp_result_gen;
END_RCPP
}
// updateEta3
void updateEta3(arma::mat Gamma, arma::mat Lambda, arma::vec sigma2, arma::vec sigma1, arma::cube Theta, arma::mat H, arma::mat X, arma::mat Beta, arma::cube& eta);
RcppExport SEXP _LFBayes_updateEta3(SEXP GammaSEXP, SEXP LambdaSEXP, SEXP sigma2SEXP, SEXP sigma1SEXP, SEXP ThetaSEXP, SEXP HSEXP, SEXP XSEXP, SEXP BetaSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type H(HSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Beta(BetaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type eta(etaSEXP);
    updateEta3(Gamma, Lambda, sigma2, sigma1, Theta, H, X, Beta, eta);
    return R_NilValue;
END_RCPP
}
// updateEta3Sig
void updateEta3Sig(arma::mat Gamma, arma::mat Lambda, arma::mat Sigma, arma::cube Theta, arma::mat H, arma::mat X, arma::mat Beta, arma::cube& eta);
RcppExport SEXP _LFBayes_updateEta3Sig(SEXP GammaSEXP, SEXP LambdaSEXP, SEXP SigmaSEXP, SEXP ThetaSEXP, SEXP HSEXP, SEXP XSEXP, SEXP BetaSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type H(HSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Beta(BetaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type eta(etaSEXP);
    updateEta3Sig(Gamma, Lambda, Sigma, Theta, H, X, Beta, eta);
    return R_NilValue;
END_RCPP
}
// updateGamma
void updateGamma(arma::cube& eta, arma::mat& Lambda, arma::vec Deltastar, arma::mat& Phistar, arma::vec sigma1, arma::vec sigma2, arma::cube& theta, arma::mat& Gamma);
RcppExport SEXP _LFBayes_updateGamma(SEXP etaSEXP, SEXP LambdaSEXP, SEXP DeltastarSEXP, SEXP PhistarSEXP, SEXP sigma1SEXP, SEXP sigma2SEXP, SEXP thetaSEXP, SEXP GammaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Deltastar(DeltastarSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Phistar(PhistarSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Gamma(GammaSEXP);
    updateGamma(eta, Lambda, Deltastar, Phistar, sigma1, sigma2, theta, Gamma);
    return R_NilValue;
END_RCPP
}
// updateGammaSig
void updateGammaSig(arma::cube& eta, arma::mat& Lambda, arma::vec Deltastar, arma::mat& Phistar, arma::mat Sigma, arma::cube& theta, arma::mat& Gamma);
RcppExport SEXP _LFBayes_updateGammaSig(SEXP etaSEXP, SEXP LambdaSEXP, SEXP DeltastarSEXP, SEXP PhistarSEXP, SEXP SigmaSEXP, SEXP thetaSEXP, SEXP GammaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Deltastar(DeltastarSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Phistar(PhistarSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Gamma(GammaSEXP);
    updateGammaSig(eta, Lambda, Deltastar, Phistar, Sigma, theta, Gamma);
    return R_NilValue;
END_RCPP
}
// updateH
arma::mat updateH(arma::cube& eta, arma::mat& beta, arma::mat& X);
RcppExport SEXP _LFBayes_updateH(SEXP etaSEXP, SEXP betaSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(updateH(eta, beta, X));
    return rcpp_result_gen;
END_RCPP
}
// updateHb
double updateHb(arma::mat H);
RcppExport SEXP _LFBayes_updateHb(SEXP HSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type H(HSEXP);
    rcpp_result_gen = Rcpp::wrap(updateHb(H));
    return rcpp_result_gen;
END_RCPP
}
// updateHProd
arma::vec updateHProd(arma::cube Eta, arma::mat beta, arma::mat X, arma::vec Delta);
RcppExport SEXP _LFBayes_updateHProd(SEXP EtaSEXP, SEXP betaSEXP, SEXP XSEXP, SEXP DeltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateHProd(Eta, beta, X, Delta));
    return rcpp_result_gen;
END_RCPP
}
// updateLambda
void updateLambda(arma::cube& eta, arma::mat& Gamma, arma::vec Delta, arma::mat& Phi, arma::vec sigma1, arma::vec sigma2, arma::cube& theta, arma::mat& Lambda);
RcppExport SEXP _LFBayes_updateLambda(SEXP etaSEXP, SEXP GammaSEXP, SEXP DeltaSEXP, SEXP PhiSEXP, SEXP sigma1SEXP, SEXP sigma2SEXP, SEXP thetaSEXP, SEXP LambdaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Lambda(LambdaSEXP);
    updateLambda(eta, Gamma, Delta, Phi, sigma1, sigma2, theta, Lambda);
    return R_NilValue;
END_RCPP
}
// updateLambdaMH
arma::mat updateLambdaMH(arma::mat Lambda, arma::mat Gamma, arma::cube& theta, arma::cube& eta, arma::mat Sigma, arma::mat H);
RcppExport SEXP _LFBayes_updateLambdaMH(SEXP LambdaSEXP, SEXP GammaSEXP, SEXP thetaSEXP, SEXP etaSEXP, SEXP SigmaSEXP, SEXP HSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type H(HSEXP);
    rcpp_result_gen = Rcpp::wrap(updateLambdaMH(Lambda, Gamma, theta, eta, Sigma, H));
    return rcpp_result_gen;
END_RCPP
}
// updateLambdaSig
void updateLambdaSig(arma::cube& eta, arma::mat& Gamma, arma::vec Delta, arma::mat& Phi, arma::mat Sigma, arma::cube& theta, arma::mat& Lambda);
RcppExport SEXP _LFBayes_updateLambdaSig(SEXP etaSEXP, SEXP GammaSEXP, SEXP DeltaSEXP, SEXP PhiSEXP, SEXP SigmaSEXP, SEXP thetaSEXP, SEXP LambdaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Lambda(LambdaSEXP);
    updateLambdaSig(eta, Gamma, Delta, Phi, Sigma, theta, Lambda);
    return R_NilValue;
END_RCPP
}
// updateLambdaSigTest
arma::mat updateLambdaSigTest(arma::cube& eta, arma::mat& Gamma, arma::vec Delta, arma::mat& Phi, arma::mat Sigma, arma::cube& theta, arma::mat& Lambda);
RcppExport SEXP _LFBayes_updateLambdaSigTest(SEXP etaSEXP, SEXP GammaSEXP, SEXP DeltaSEXP, SEXP PhiSEXP, SEXP SigmaSEXP, SEXP thetaSEXP, SEXP LambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Lambda(LambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateLambdaSigTest(eta, Gamma, Delta, Phi, Sigma, theta, Lambda));
    return rcpp_result_gen;
END_RCPP
}
// updateLambda2
arma::mat updateLambda2(arma::mat Theta, arma::mat eta, arma::vec Sigma, arma::vec Tau);
RcppExport SEXP _LFBayes_updateLambda2(SEXP ThetaSEXP, SEXP etaSEXP, SEXP SigmaSEXP, SEXP TauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Tau(TauSEXP);
    rcpp_result_gen = Rcpp::wrap(updateLambda2(Theta, eta, Sigma, Tau));
    return rcpp_result_gen;
END_RCPP
}
// updateLambda3
arma::mat updateLambda3(arma::mat Theta, arma::mat eta, arma::vec Sigma, arma::mat Phi, arma::vec Delta);
RcppExport SEXP _LFBayes_updateLambda3(SEXP ThetaSEXP, SEXP etaSEXP, SEXP SigmaSEXP, SEXP PhiSEXP, SEXP DeltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateLambda3(Theta, eta, Sigma, Phi, Delta));
    return rcpp_result_gen;
END_RCPP
}
// updatePhi
arma::mat updatePhi(arma::mat& Lambda, arma::vec delta);
RcppExport SEXP _LFBayes_updatePhi(SEXP LambdaSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(updatePhi(Lambda, delta));
    return rcpp_result_gen;
END_RCPP
}
// updateSigma1
arma::vec updateSigma1(arma::cube& eta, arma::cube& theta, arma::mat& Lambda, arma::mat& Gamma, arma::vec sigma2);
RcppExport SEXP _LFBayes_updateSigma1(SEXP etaSEXP, SEXP thetaSEXP, SEXP LambdaSEXP, SEXP GammaSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(updateSigma1(eta, theta, Lambda, Gamma, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// updateSigma2
arma::vec updateSigma2(arma::mat Theta, arma::mat Lambda, arma::mat Eta);
RcppExport SEXP _LFBayes_updateSigma2(SEXP ThetaSEXP, SEXP LambdaSEXP, SEXP EtaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Eta(EtaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateSigma2(Theta, Lambda, Eta));
    return rcpp_result_gen;
END_RCPP
}
// updateSigma
arma::mat updateSigma(arma::mat Lambda, arma::mat Gamma, arma::cube Theta, arma::cube Eta);
RcppExport SEXP _LFBayes_updateSigma(SEXP LambdaSEXP, SEXP GammaSEXP, SEXP ThetaSEXP, SEXP EtaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Eta(EtaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateSigma(Lambda, Gamma, Theta, Eta));
    return rcpp_result_gen;
END_RCPP
}
// updateTheta
arma::cube updateTheta(arma::mat& Lambda, arma::mat& Gamma, arma::vec sigma1, arma::vec sigma2, arma::cube& eta, arma::mat& splineS, arma::mat& splineT, arma::mat& y, double varphi);
RcppExport SEXP _LFBayes_updateTheta(SEXP LambdaSEXP, SEXP GammaSEXP, SEXP sigma1SEXP, SEXP sigma2SEXP, SEXP etaSEXP, SEXP splineSSEXP, SEXP splineTSEXP, SEXP ySEXP, SEXP varphiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type splineS(splineSSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type splineT(splineTSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type varphi(varphiSEXP);
    rcpp_result_gen = Rcpp::wrap(updateTheta(Lambda, Gamma, sigma1, sigma2, eta, splineS, splineT, y, varphi));
    return rcpp_result_gen;
END_RCPP
}
// updateThetaSig
arma::cube updateThetaSig(arma::mat& Lambda, arma::mat& Gamma, arma::mat Sigma, arma::cube& eta, arma::mat& splineS, arma::mat& splineT, arma::mat& y, double varphi);
RcppExport SEXP _LFBayes_updateThetaSig(SEXP LambdaSEXP, SEXP GammaSEXP, SEXP SigmaSEXP, SEXP etaSEXP, SEXP splineSSEXP, SEXP splineTSEXP, SEXP ySEXP, SEXP varphiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type splineS(splineSSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type splineT(splineTSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type varphi(varphiSEXP);
    rcpp_result_gen = Rcpp::wrap(updateThetaSig(Lambda, Gamma, Sigma, eta, splineS, splineT, y, varphi));
    return rcpp_result_gen;
END_RCPP
}
// updateTheta2
arma::mat updateTheta2(arma::mat Lambda, arma::vec Sigma, arma::mat eta, arma::mat Data, double Varphi, arma::mat Basis);
RcppExport SEXP _LFBayes_updateTheta2(SEXP LambdaSEXP, SEXP SigmaSEXP, SEXP etaSEXP, SEXP DataSEXP, SEXP VarphiSEXP, SEXP BasisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Data(DataSEXP);
    Rcpp::traits::input_parameter< double >::type Varphi(VarphiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Basis(BasisSEXP);
    rcpp_result_gen = Rcpp::wrap(updateTheta2(Lambda, Sigma, eta, Data, Varphi, Basis));
    return rcpp_result_gen;
END_RCPP
}
// updateVarphi
double updateVarphi(arma::cube& theta, arma::mat& splineS, arma::mat& splineT, arma::mat& y);
RcppExport SEXP _LFBayes_updateVarphi(SEXP thetaSEXP, SEXP splineSSEXP, SEXP splineTSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type splineS(splineSSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type splineT(splineTSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(updateVarphi(theta, splineS, splineT, y));
    return rcpp_result_gen;
END_RCPP
}
// updateVarphi2
double updateVarphi2(arma::mat Data, arma::mat Theta, arma::mat Basis);
RcppExport SEXP _LFBayes_updateVarphi2(SEXP DataSEXP, SEXP ThetaSEXP, SEXP BasisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Data(DataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Basis(BasisSEXP);
    rcpp_result_gen = Rcpp::wrap(updateVarphi2(Data, Theta, Basis));
    return rcpp_result_gen;
END_RCPP
}
// initializeY
arma::vec initializeY(arma::vec x, arma::vec missing, int s, int t);
RcppExport SEXP _LFBayes_initializeY(SEXP xSEXP, SEXP missingSEXP, SEXP sSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type missing(missingSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(initializeY(x, missing, s, t));
    return rcpp_result_gen;
END_RCPP
}
// getPenalty
arma::mat getPenalty(arma::uword n);
RcppExport SEXP _LFBayes_getPenalty(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(getPenalty(n));
    return rcpp_result_gen;
END_RCPP
}
// updatea1
double updatea1(arma::vec Delta, double a1);
RcppExport SEXP _LFBayes_updatea1(SEXP DeltaSEXP, SEXP a1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< double >::type a1(a1SEXP);
    rcpp_result_gen = Rcpp::wrap(updatea1(Delta, a1));
    return rcpp_result_gen;
END_RCPP
}
// updatea2
double updatea2(arma::vec Delta, double a2);
RcppExport SEXP _LFBayes_updatea2(SEXP DeltaSEXP, SEXP a2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< double >::type a2(a2SEXP);
    rcpp_result_gen = Rcpp::wrap(updatea2(Delta, a2));
    return rcpp_result_gen;
END_RCPP
}
// updateLambdaSmooth
arma::mat updateLambdaSmooth(arma::cube Eta, arma::mat Gamma, arma::vec Sigma1, arma::vec Sigma2, arma::vec Tau, arma::cube Theta);
RcppExport SEXP _LFBayes_updateLambdaSmooth(SEXP EtaSEXP, SEXP GammaSEXP, SEXP Sigma1SEXP, SEXP Sigma2SEXP, SEXP TauSEXP, SEXP ThetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Sigma1(Sigma1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Sigma2(Sigma2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Tau(TauSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Theta(ThetaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateLambdaSmooth(Eta, Gamma, Sigma1, Sigma2, Tau, Theta));
    return rcpp_result_gen;
END_RCPP
}
// updateLambda4
arma::mat updateLambda4(arma::mat Theta, arma::mat eta, arma::vec Sigma, arma::vec Delta);
RcppExport SEXP _LFBayes_updateLambda4(SEXP ThetaSEXP, SEXP etaSEXP, SEXP SigmaSEXP, SEXP DeltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateLambda4(Theta, eta, Sigma, Delta));
    return rcpp_result_gen;
END_RCPP
}
// updateLambdaSmoothD
arma::mat updateLambdaSmoothD(arma::cube Eta, arma::mat Gamma, arma::vec Sigma1, arma::vec Sigma2, arma::vec Delta, arma::cube Theta);
RcppExport SEXP _LFBayes_updateLambdaSmoothD(SEXP EtaSEXP, SEXP GammaSEXP, SEXP Sigma1SEXP, SEXP Sigma2SEXP, SEXP DeltaSEXP, SEXP ThetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Sigma1(Sigma1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Sigma2(Sigma2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Theta(ThetaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateLambdaSmoothD(Eta, Gamma, Sigma1, Sigma2, Delta, Theta));
    return rcpp_result_gen;
END_RCPP
}
// updateLambdaSmoothDSig
arma::mat updateLambdaSmoothDSig(arma::cube Eta, arma::mat Gamma, arma::mat Sigma, arma::vec Delta, arma::cube Theta);
RcppExport SEXP _LFBayes_updateLambdaSmoothDSig(SEXP EtaSEXP, SEXP GammaSEXP, SEXP SigmaSEXP, SEXP DeltaSEXP, SEXP ThetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Theta(ThetaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateLambdaSmoothDSig(Eta, Gamma, Sigma, Delta, Theta));
    return rcpp_result_gen;
END_RCPP
}
// updateGammaSmoothDSig
arma::mat updateGammaSmoothDSig(arma::cube Eta, arma::mat Lambda, arma::mat Sigma, arma::vec Delta, arma::cube Theta);
RcppExport SEXP _LFBayes_updateGammaSmoothDSig(SEXP EtaSEXP, SEXP LambdaSEXP, SEXP SigmaSEXP, SEXP DeltaSEXP, SEXP ThetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Theta(ThetaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateGammaSmoothDSig(Eta, Lambda, Sigma, Delta, Theta));
    return rcpp_result_gen;
END_RCPP
}
// updateGammaSmooth
arma::mat updateGammaSmooth(arma::cube Eta, arma::mat Lambda, arma::vec Sigma1, arma::vec Sigma2, arma::vec Tau, arma::cube Theta);
RcppExport SEXP _LFBayes_updateGammaSmooth(SEXP EtaSEXP, SEXP LambdaSEXP, SEXP Sigma1SEXP, SEXP Sigma2SEXP, SEXP TauSEXP, SEXP ThetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Sigma1(Sigma1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Sigma2(Sigma2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Tau(TauSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Theta(ThetaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateGammaSmooth(Eta, Lambda, Sigma1, Sigma2, Tau, Theta));
    return rcpp_result_gen;
END_RCPP
}
// updateGammaSmoothD
arma::mat updateGammaSmoothD(arma::cube Eta, arma::mat Lambda, arma::vec Sigma1, arma::vec Sigma2, arma::vec Delta, arma::cube Theta);
RcppExport SEXP _LFBayes_updateGammaSmoothD(SEXP EtaSEXP, SEXP LambdaSEXP, SEXP Sigma1SEXP, SEXP Sigma2SEXP, SEXP DeltaSEXP, SEXP ThetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Sigma1(Sigma1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Sigma2(Sigma2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Theta(ThetaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateGammaSmoothD(Eta, Lambda, Sigma1, Sigma2, Delta, Theta));
    return rcpp_result_gen;
END_RCPP
}
// updateTau
arma::vec updateTau(arma::mat Lambda);
RcppExport SEXP _LFBayes_updateTau(SEXP LambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateTau(Lambda));
    return rcpp_result_gen;
END_RCPP
}
// updateDeltaProd
arma::vec updateDeltaProd(arma::mat Lambda, arma::vec Delta);
RcppExport SEXP _LFBayes_updateDeltaProd(SEXP LambdaSEXP, SEXP DeltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateDeltaProd(Lambda, Delta));
    return rcpp_result_gen;
END_RCPP
}
// FuncProcess
arma::mat FuncProcess(arma::mat Y, arma::mat splineS, arma::mat splineT);
RcppExport SEXP _LFBayes_FuncProcess(SEXP YSEXP, SEXP splineSSEXP, SEXP splineTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineS(splineSSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineT(splineTSEXP);
    rcpp_result_gen = Rcpp::wrap(FuncProcess(Y, splineS, splineT));
    return rcpp_result_gen;
END_RCPP
}
// LongProcess
arma::mat LongProcess(arma::mat Y, arma::mat splineS, arma::mat splineT);
RcppExport SEXP _LFBayes_LongProcess(SEXP YSEXP, SEXP splineSSEXP, SEXP splineTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineS(splineSSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type splineT(splineTSEXP);
    rcpp_result_gen = Rcpp::wrap(LongProcess(Y, splineS, splineT));
    return rcpp_result_gen;
END_RCPP
}
// updateDeltaProdPCA
arma::vec updateDeltaProdPCA(arma::mat Lambda, arma::vec Delta, arma::vec Alpha, double a1, double a2);
RcppExport SEXP _LFBayes_updateDeltaProdPCA(SEXP LambdaSEXP, SEXP DeltaSEXP, SEXP AlphaSEXP, SEXP a1SEXP, SEXP a2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Alpha(AlphaSEXP);
    Rcpp::traits::input_parameter< double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< double >::type a2(a2SEXP);
    rcpp_result_gen = Rcpp::wrap(updateDeltaProdPCA(Lambda, Delta, Alpha, a1, a2));
    return rcpp_result_gen;
END_RCPP
}
// mydnorm
double mydnorm(arma::vec X, arma::vec mu, arma::mat Sigma, int givelog);
RcppExport SEXP _LFBayes_mydnorm(SEXP XSEXP, SEXP muSEXP, SEXP SigmaSEXP, SEXP givelogSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< int >::type givelog(givelogSEXP);
    rcpp_result_gen = Rcpp::wrap(mydnorm(X, mu, Sigma, givelog));
    return rcpp_result_gen;
END_RCPP
}
// dmvnrm_arma
double dmvnrm_arma(arma::vec x, arma::vec mean, arma::mat sigma, bool logd);
RcppExport SEXP _LFBayes_dmvnrm_arma(SEXP xSEXP, SEXP meanSEXP, SEXP sigmaSEXP, SEXP logdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type logd(logdSEXP);
    rcpp_result_gen = Rcpp::wrap(dmvnrm_arma(x, mean, sigma, logd));
    return rcpp_result_gen;
END_RCPP
}
// rnorm_arma1
arma::vec rnorm_arma1(arma::vec mean, arma::mat precision);
RcppExport SEXP _LFBayes_rnorm_arma1(SEXP meanSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(rnorm_arma1(mean, precision));
    return rcpp_result_gen;
END_RCPP
}
// rnorm_arma2
arma::vec rnorm_arma2(arma::vec mean, arma::mat precision);
RcppExport SEXP _LFBayes_rnorm_arma2(SEXP meanSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(rnorm_arma2(mean, precision));
    return rcpp_result_gen;
END_RCPP
}
// rnorm_arma3
arma::vec rnorm_arma3(arma::vec mean, arma::mat precision);
RcppExport SEXP _LFBayes_rnorm_arma3(SEXP meanSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(rnorm_arma3(mean, precision));
    return rcpp_result_gen;
END_RCPP
}
// rnorm_arma4
arma::vec rnorm_arma4(arma::vec mean, arma::mat precision);
RcppExport SEXP _LFBayes_rnorm_arma4(SEXP meanSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(rnorm_arma4(mean, precision));
    return rcpp_result_gen;
END_RCPP
}
// updateAlphaPCA
arma::vec updateAlphaPCA(arma::mat Lambda, arma::vec Delta, arma::vec Alpha);
RcppExport SEXP _LFBayes_updateAlphaPCA(SEXP LambdaSEXP, SEXP DeltaSEXP, SEXP AlphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Alpha(AlphaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateAlphaPCA(Lambda, Delta, Alpha));
    return rcpp_result_gen;
END_RCPP
}
// updateLambdaPCA
arma::mat updateLambdaPCA(arma::cube Eta, arma::mat Gamma, arma::mat Sigma, arma::vec Delta, arma::vec Alpha, arma::cube Theta);
RcppExport SEXP _LFBayes_updateLambdaPCA(SEXP EtaSEXP, SEXP GammaSEXP, SEXP SigmaSEXP, SEXP DeltaSEXP, SEXP AlphaSEXP, SEXP ThetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Alpha(AlphaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Theta(ThetaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateLambdaPCA(Eta, Gamma, Sigma, Delta, Alpha, Theta));
    return rcpp_result_gen;
END_RCPP
}
// updateGammaPCA
arma::mat updateGammaPCA(arma::cube Eta, arma::mat Lambda, arma::mat Sigma, arma::vec Delta, arma::vec Alpha, arma::cube Theta);
RcppExport SEXP _LFBayes_updateGammaPCA(SEXP EtaSEXP, SEXP LambdaSEXP, SEXP SigmaSEXP, SEXP DeltaSEXP, SEXP AlphaSEXP, SEXP ThetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Alpha(AlphaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Theta(ThetaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateGammaPCA(Eta, Lambda, Sigma, Delta, Alpha, Theta));
    return rcpp_result_gen;
END_RCPP
}
// gam_trunc_left
double gam_trunc_left(double a, double b, double cut);
RcppExport SEXP _LFBayes_gam_trunc_left(SEXP aSEXP, SEXP bSEXP, SEXP cutSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type cut(cutSEXP);
    rcpp_result_gen = Rcpp::wrap(gam_trunc_left(a, b, cut));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LFBayes_calculate_WAIC", (DL_FUNC) &_LFBayes_calculate_WAIC, 6},
    {"_LFBayes_calculate_BIC", (DL_FUNC) &_LFBayes_calculate_BIC, 7},
    {"_LFBayes_calculate_DIC", (DL_FUNC) &_LFBayes_calculate_DIC, 7},
    {"_LFBayes_calculate_BIC_Missing", (DL_FUNC) &_LFBayes_calculate_BIC_Missing, 8},
    {"_LFBayes_calculate_DIC_Missing", (DL_FUNC) &_LFBayes_calculate_DIC_Missing, 8},
    {"_LFBayes_test1", (DL_FUNC) &_LFBayes_test1, 2},
    {"_LFBayes_eigenLF", (DL_FUNC) &_LFBayes_eigenLF, 5},
    {"_LFBayes_eigenLFChains", (DL_FUNC) &_LFBayes_eigenLFChains, 10},
    {"_LFBayes_integrated_latent", (DL_FUNC) &_LFBayes_integrated_latent, 2},
    {"_LFBayes_integrated", (DL_FUNC) &_LFBayes_integrated, 2},
    {"_LFBayes_extract_eigenfn", (DL_FUNC) &_LFBayes_extract_eigenfn, 9},
    {"_LFBayes_getMarginalFunc", (DL_FUNC) &_LFBayes_getMarginalFunc, 3},
    {"_LFBayes_getMarginalLong", (DL_FUNC) &_LFBayes_getMarginalLong, 3},
    {"_LFBayes_mcmcWeak", (DL_FUNC) &_LFBayes_mcmcWeak, 10},
    {"_LFBayes_mcmcWeakChains", (DL_FUNC) &_LFBayes_mcmcWeakChains, 11},
    {"_LFBayes_mcmcWeakChainsPCA", (DL_FUNC) &_LFBayes_mcmcWeakChainsPCA, 11},
    {"_LFBayes_timesTwo", (DL_FUNC) &_LFBayes_timesTwo, 1},
    {"_LFBayes_convertToPrecision", (DL_FUNC) &_LFBayes_convertToPrecision, 3},
    {"_LFBayes_updateBeta2", (DL_FUNC) &_LFBayes_updateBeta2, 3},
    {"_LFBayes_updateBetaProd", (DL_FUNC) &_LFBayes_updateBetaProd, 5},
    {"_LFBayes_updateDelta3", (DL_FUNC) &_LFBayes_updateDelta3, 5},
    {"_LFBayes_updateDeltaProdTemp", (DL_FUNC) &_LFBayes_updateDeltaProdTemp, 4},
    {"_LFBayes_updateE", (DL_FUNC) &_LFBayes_updateE, 1},
    {"_LFBayes_updateEta", (DL_FUNC) &_LFBayes_updateEta, 12},
    {"_LFBayes_updateEtaSig", (DL_FUNC) &_LFBayes_updateEtaSig, 11},
    {"_LFBayes_updateEta2", (DL_FUNC) &_LFBayes_updateEta2, 7},
    {"_LFBayes_updateEta3", (DL_FUNC) &_LFBayes_updateEta3, 9},
    {"_LFBayes_updateEta3Sig", (DL_FUNC) &_LFBayes_updateEta3Sig, 8},
    {"_LFBayes_updateGamma", (DL_FUNC) &_LFBayes_updateGamma, 8},
    {"_LFBayes_updateGammaSig", (DL_FUNC) &_LFBayes_updateGammaSig, 7},
    {"_LFBayes_updateH", (DL_FUNC) &_LFBayes_updateH, 3},
    {"_LFBayes_updateHb", (DL_FUNC) &_LFBayes_updateHb, 1},
    {"_LFBayes_updateHProd", (DL_FUNC) &_LFBayes_updateHProd, 4},
    {"_LFBayes_updateLambda", (DL_FUNC) &_LFBayes_updateLambda, 8},
    {"_LFBayes_updateLambdaMH", (DL_FUNC) &_LFBayes_updateLambdaMH, 6},
    {"_LFBayes_updateLambdaSig", (DL_FUNC) &_LFBayes_updateLambdaSig, 7},
    {"_LFBayes_updateLambdaSigTest", (DL_FUNC) &_LFBayes_updateLambdaSigTest, 7},
    {"_LFBayes_updateLambda2", (DL_FUNC) &_LFBayes_updateLambda2, 4},
    {"_LFBayes_updateLambda3", (DL_FUNC) &_LFBayes_updateLambda3, 5},
    {"_LFBayes_updatePhi", (DL_FUNC) &_LFBayes_updatePhi, 2},
    {"_LFBayes_updateSigma1", (DL_FUNC) &_LFBayes_updateSigma1, 5},
    {"_LFBayes_updateSigma2", (DL_FUNC) &_LFBayes_updateSigma2, 3},
    {"_LFBayes_updateSigma", (DL_FUNC) &_LFBayes_updateSigma, 4},
    {"_LFBayes_updateTheta", (DL_FUNC) &_LFBayes_updateTheta, 9},
    {"_LFBayes_updateThetaSig", (DL_FUNC) &_LFBayes_updateThetaSig, 8},
    {"_LFBayes_updateTheta2", (DL_FUNC) &_LFBayes_updateTheta2, 6},
    {"_LFBayes_updateVarphi", (DL_FUNC) &_LFBayes_updateVarphi, 4},
    {"_LFBayes_updateVarphi2", (DL_FUNC) &_LFBayes_updateVarphi2, 3},
    {"_LFBayes_initializeY", (DL_FUNC) &_LFBayes_initializeY, 4},
    {"_LFBayes_getPenalty", (DL_FUNC) &_LFBayes_getPenalty, 1},
    {"_LFBayes_updatea1", (DL_FUNC) &_LFBayes_updatea1, 2},
    {"_LFBayes_updatea2", (DL_FUNC) &_LFBayes_updatea2, 2},
    {"_LFBayes_updateLambdaSmooth", (DL_FUNC) &_LFBayes_updateLambdaSmooth, 6},
    {"_LFBayes_updateLambda4", (DL_FUNC) &_LFBayes_updateLambda4, 4},
    {"_LFBayes_updateLambdaSmoothD", (DL_FUNC) &_LFBayes_updateLambdaSmoothD, 6},
    {"_LFBayes_updateLambdaSmoothDSig", (DL_FUNC) &_LFBayes_updateLambdaSmoothDSig, 5},
    {"_LFBayes_updateGammaSmoothDSig", (DL_FUNC) &_LFBayes_updateGammaSmoothDSig, 5},
    {"_LFBayes_updateGammaSmooth", (DL_FUNC) &_LFBayes_updateGammaSmooth, 6},
    {"_LFBayes_updateGammaSmoothD", (DL_FUNC) &_LFBayes_updateGammaSmoothD, 6},
    {"_LFBayes_updateTau", (DL_FUNC) &_LFBayes_updateTau, 1},
    {"_LFBayes_updateDeltaProd", (DL_FUNC) &_LFBayes_updateDeltaProd, 2},
    {"_LFBayes_FuncProcess", (DL_FUNC) &_LFBayes_FuncProcess, 3},
    {"_LFBayes_LongProcess", (DL_FUNC) &_LFBayes_LongProcess, 3},
    {"_LFBayes_updateDeltaProdPCA", (DL_FUNC) &_LFBayes_updateDeltaProdPCA, 5},
    {"_LFBayes_mydnorm", (DL_FUNC) &_LFBayes_mydnorm, 4},
    {"_LFBayes_dmvnrm_arma", (DL_FUNC) &_LFBayes_dmvnrm_arma, 4},
    {"_LFBayes_rnorm_arma1", (DL_FUNC) &_LFBayes_rnorm_arma1, 2},
    {"_LFBayes_rnorm_arma2", (DL_FUNC) &_LFBayes_rnorm_arma2, 2},
    {"_LFBayes_rnorm_arma3", (DL_FUNC) &_LFBayes_rnorm_arma3, 2},
    {"_LFBayes_rnorm_arma4", (DL_FUNC) &_LFBayes_rnorm_arma4, 2},
    {"_LFBayes_updateAlphaPCA", (DL_FUNC) &_LFBayes_updateAlphaPCA, 3},
    {"_LFBayes_updateLambdaPCA", (DL_FUNC) &_LFBayes_updateLambdaPCA, 6},
    {"_LFBayes_updateGammaPCA", (DL_FUNC) &_LFBayes_updateGammaPCA, 6},
    {"_LFBayes_gam_trunc_left", (DL_FUNC) &_LFBayes_gam_trunc_left, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_LFBayes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
