# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenLF <- function(splineS, splineT, mod, numeig, burnin) {
    .Call(`_LFBayes_eigenLF`, splineS, splineT, mod, numeig, burnin)
}

getMarginalFunc <- function(cov, ns, nt) {
    .Call(`_LFBayes_getMarginalFunc`, cov, ns, nt)
}

getMarginalLong <- function(cov, ns, nt) {
    .Call(`_LFBayes_getMarginalLong`, cov, ns, nt)
}

mcmcWeak <- function(y, missing, X, splineS, splineT, q1, q2, iter, thin, burnin) {
    .Call(`_LFBayes_mcmcWeak`, y, missing, X, splineS, splineT, q1, q2, iter, thin, burnin)
}

convertToPrecision <- function(Delta, q1, q2) {
    .Call(`_LFBayes_convertToPrecision`, Delta, q1, q2)
}

updateBeta2 <- function(E, Eta, X) {
    .Call(`_LFBayes_updateBeta2`, E, Eta, X)
}

updateBetaProd <- function(eta, Delta, E, X, beta) {
    invisible(.Call(`_LFBayes_updateBetaProd`, eta, Delta, E, X, beta))
}

updateDelta3 <- function(Lambda, Phi, Delta, a1, a2) {
    .Call(`_LFBayes_updateDelta3`, Lambda, Phi, Delta, a1, a2)
}

updateDeltaProdTemp <- function(Lambda, Delta, a1, a2) {
    .Call(`_LFBayes_updateDeltaProdTemp`, Lambda, Delta, a1, a2)
}

updateE <- function(beta) {
    .Call(`_LFBayes_updateE`, beta)
}

updateEta <- function(Lambda, Gamma, sigma1, sigma2, H, splineS, splineT, y, varphi, beta, X, eta) {
    invisible(.Call(`_LFBayes_updateEta`, Lambda, Gamma, sigma1, sigma2, H, splineS, splineT, y, varphi, beta, X, eta))
}

updateEta2 <- function(Lambda, Basis, Sigma, Data, Beta, X, Varphi) {
    .Call(`_LFBayes_updateEta2`, Lambda, Basis, Sigma, Data, Beta, X, Varphi)
}

updateEta3 <- function(Gamma, Lambda, sigma2, sigma1, Theta, H, X, Beta, eta) {
    invisible(.Call(`_LFBayes_updateEta3`, Gamma, Lambda, sigma2, sigma1, Theta, H, X, Beta, eta))
}

updateEta3Sig <- function(Gamma, Lambda, Sigma, Theta, H, X, Beta, eta) {
    invisible(.Call(`_LFBayes_updateEta3Sig`, Gamma, Lambda, Sigma, Theta, H, X, Beta, eta))
}

updateEtaProd <- function(Lambda, Gamma, sigma1, sigma2, Delta, splineS, splineT, y, varphi, beta, X, eta) {
    invisible(.Call(`_LFBayes_updateEtaProd`, Lambda, Gamma, sigma1, sigma2, Delta, splineS, splineT, y, varphi, beta, X, eta))
}

updateGamma <- function(eta, Lambda, Deltastar, Phistar, sigma1, sigma2, theta, Gamma) {
    invisible(.Call(`_LFBayes_updateGamma`, eta, Lambda, Deltastar, Phistar, sigma1, sigma2, theta, Gamma))
}

updateGammaSig <- function(eta, Lambda, Deltastar, Phistar, Sigma, theta, Gamma) {
    invisible(.Call(`_LFBayes_updateGammaSig`, eta, Lambda, Deltastar, Phistar, Sigma, theta, Gamma))
}

updateH <- function(eta, beta, X) {
    .Call(`_LFBayes_updateH`, eta, beta, X)
}

updateHb <- function(H) {
    .Call(`_LFBayes_updateHb`, H)
}

updateHProd <- function(Eta, beta, X, Delta) {
    .Call(`_LFBayes_updateHProd`, Eta, beta, X, Delta)
}

updateLambda <- function(eta, Gamma, Delta, Phi, sigma1, sigma2, theta, Lambda) {
    invisible(.Call(`_LFBayes_updateLambda`, eta, Gamma, Delta, Phi, sigma1, sigma2, theta, Lambda))
}

updateLambdaSig <- function(eta, Gamma, Delta, Phi, Sigma, theta, Lambda) {
    invisible(.Call(`_LFBayes_updateLambdaSig`, eta, Gamma, Delta, Phi, Sigma, theta, Lambda))
}

updateLambda2 <- function(Theta, eta, Sigma, Tau) {
    .Call(`_LFBayes_updateLambda2`, Theta, eta, Sigma, Tau)
}

updateLambda3 <- function(Theta, eta, Sigma, Phi, Delta) {
    .Call(`_LFBayes_updateLambda3`, Theta, eta, Sigma, Phi, Delta)
}

updatePhi <- function(Lambda, delta) {
    .Call(`_LFBayes_updatePhi`, Lambda, delta)
}

updateSigma1 <- function(eta, theta, Lambda, Gamma, sigma2) {
    .Call(`_LFBayes_updateSigma1`, eta, theta, Lambda, Gamma, sigma2)
}

updateSigma2 <- function(Theta, Lambda, Eta) {
    .Call(`_LFBayes_updateSigma2`, Theta, Lambda, Eta)
}

updateSigma <- function(Lambda, Gamma, Theta, Eta) {
    .Call(`_LFBayes_updateSigma`, Lambda, Gamma, Theta, Eta)
}

updateTheta <- function(Lambda, Gamma, sigma1, sigma2, eta, splineS, splineT, y, varphi) {
    .Call(`_LFBayes_updateTheta`, Lambda, Gamma, sigma1, sigma2, eta, splineS, splineT, y, varphi)
}

updateThetaSig <- function(Lambda, Gamma, Sigma, eta, splineS, splineT, y, varphi) {
    .Call(`_LFBayes_updateThetaSig`, Lambda, Gamma, Sigma, eta, splineS, splineT, y, varphi)
}

updateTheta2 <- function(Lambda, Sigma, eta, Data, Varphi, Basis) {
    .Call(`_LFBayes_updateTheta2`, Lambda, Sigma, eta, Data, Varphi, Basis)
}

updateVarphi <- function(theta, splineS, splineT, y) {
    .Call(`_LFBayes_updateVarphi`, theta, splineS, splineT, y)
}

updateVarphi2 <- function(Data, Theta, Basis) {
    .Call(`_LFBayes_updateVarphi2`, Data, Theta, Basis)
}

updatea1 <- function(Delta, a1) {
    .Call(`_LFBayes_updatea1`, Delta, a1)
}

updatea2 <- function(Delta, a2) {
    .Call(`_LFBayes_updatea2`, Delta, a2)
}

updateLambdaSmooth <- function(Eta, Gamma, Sigma1, Sigma2, Tau, Theta) {
    .Call(`_LFBayes_updateLambdaSmooth`, Eta, Gamma, Sigma1, Sigma2, Tau, Theta)
}

updateLambda4 <- function(Theta, eta, Sigma, Delta) {
    .Call(`_LFBayes_updateLambda4`, Theta, eta, Sigma, Delta)
}

updateLambdaSmoothD <- function(Eta, Gamma, Sigma1, Sigma2, Delta, Theta) {
    .Call(`_LFBayes_updateLambdaSmoothD`, Eta, Gamma, Sigma1, Sigma2, Delta, Theta)
}

updateGammaSmooth <- function(Eta, Lambda, Sigma1, Sigma2, Tau, Theta) {
    .Call(`_LFBayes_updateGammaSmooth`, Eta, Lambda, Sigma1, Sigma2, Tau, Theta)
}

updateGammaSmoothD <- function(Eta, Lambda, Sigma1, Sigma2, Delta, Theta) {
    .Call(`_LFBayes_updateGammaSmoothD`, Eta, Lambda, Sigma1, Sigma2, Delta, Theta)
}

updateTau <- function(Lambda) {
    .Call(`_LFBayes_updateTau`, Lambda)
}

updateDeltaProd <- function(Lambda, Delta) {
    .Call(`_LFBayes_updateDeltaProd`, Lambda, Delta)
}

FuncProcess <- function(Y, splineS, splineT) {
    .Call(`_LFBayes_FuncProcess`, Y, splineS, splineT)
}

LongProcess <- function(Y, splineS, splineT) {
    .Call(`_LFBayes_LongProcess`, Y, splineS, splineT)
}

